 /**
 *  \file    KsCmakeDef.hpp
 *  \brief   This File is generated by CMAKE
 */

/* ! -- Do Not Hand Edit - This File is generated by CMAKE -- ! */

#ifndef _KS_CONFIG_H
#define _KS_CONFIG_H

/** KernelShark Version number. */
#define KS_VERSION_STRING "2.1.0"

/** KernelShark installation prefix path. */
#define _INSTALL_PREFIX "/usr/local"

/** KernelShark plugins installation prefix path. */
#define KS_PLUGIN_INSTALL_PREFIX "/usr/local/lib64/kernelshark/plugins"

/** Location of the trace-cmd executable. */
#define TRACECMD_EXECUTABLE "/usr/local/bin/trace-cmd"

/** "pkexec" executable. */
#define DO_AS_ROOT "/usr/bin/pkexec"

/** GLUT has been found. */
#define GLUT_FOUND

/** Truetype font file. */
#define TT_FONT_FILE "/usr/share/fonts/truetype/freefont/FreeSans.ttf"

/** Qt - old version detected. */
/* #undef QT_VERSION_LESS_5_11 */
/* #undef QT_VERSION_LESS_5_15 */

/** Location of the KernelShark tests. */
/* #undef KS_TEST_DIR */

/** Semicolon-separated list of plugin names. */
#define KS_BUILTIN_PLUGINS "sched_events;event_field_plot;latency_plot;kvm_combo;missed_events"

#endif // _KS_CONFIG_H
