/* This file is automatically generated. Do not modify. */
#define VERSION_CODE 770
#define EXTRAVERSION  0
#define VERSION_STRING "3.2.0"
#define FILE_VERSION 
#define VERSION_GIT "not-a-git-repo"
