site_name: Masterthesis Documentation
# site_url: https://www.example.com
# repo_url: https://github.com/username/repo
# repo_name: GitHub
# edit_uri: edit/master/docs/
site_description: My awesome docs
site_author: Halil Pamuk
theme:
  name: material
  #features:
  #- navigation.instant
  #- navigation.tabs
  #- navigation.tabs.sticky
  #- navigation.progress
  #- navigation.tabs.expanded
  palette:
    primary: blue
    scheme: slate
  logo: 'resources/mkdocs/robot2.png'
  favicon: 'resources/mkdocs/robot2.png'
#extra_css:
#  - css/extra.css
#extra_javascript:
#  - js/extra.js
plugins:
  - exclude:
      glob:
        - "*.dat"
        - themes.md
        - "*.tmp"
        - "*.gz"
        - "*sigmatek/trace-cmd/test_trace-cmd/twocpus/*"
        - "*linux_kernels/*"
        #- "*sigmatek/xenomai/vapic/*.md"
        #- "*sigmatek/xenomai/0hardware/*.md"
        #- "*sigmatek/xenomai/1default/*.md"
        #- "*sigmatek/xenomai/2taskset/*.md"
        #- "*sigmatek/xenomai/*r*/*.md"
        #- "*sigmatek/xenomai/xenomai_suite/*"
        #- "*resources/pdfs/papers/papers.md*"
        - "*sigmatek/xenomai/xenomai_suite/sigmatek-salamander-glibc-x86_64-salamander-image-core2-64-toolchain-09.07.120_RC2.sh*"        
      regex:
        - '.*.(tmp|bin|tar)$'
  - search
markdown_extensions:
  - pymdownx.arithmatex: # For rendering block and inline math equations
      generic: true
  - pymdownx.betterem: # Improves emphasis detection for bold and italic text
  - pymdownx.caret: # Adds ability to highlight text and define sub- and superscript
  - pymdownx.mark: # Companion to caret, for highlighting text
  - pymdownx.tilde: # Companion to caret, for sub- and superscript
  - pymdownx.critic: # For tracking changes in Markdown with Critic Markup
  - pymdownx.details: # Makes Admonition call-outs collapsible
  - pymdownx.emoji: # Inlines emojis and icons in *.svg format into HTML
  - pymdownx.highlight: # Adds syntax highlighting for code blocks
  - pymdownx.inlinehilite: # Syntax highlighting for inline code
  - pymdownx.keys: # For rendering keyboard keys and combinations
  - pymdownx.smartsymbols: # Converts character sequences to corresponding symbols
  - pymdownx.snippets: # Embed content from files into documents
  - pymdownx.superfences: # Allows nesting of code/content blocks
  - pymdownx.tabbed: # Groups related content under accessible tabs
  - pymdownx.tasklist: # GitHub Flavored Markdown inspired task lists
      custom_checkbox: true
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables

  

